[package]
name = "basic-api-rust-rocket"
version = "0.1.0"
authors = ["Daniel Tebbutt <moeruze.burning@gmail.com>"]

[dependencies]
rocket = "0.2.8"
rocket_codegen = "0.2.8"
rocket_contrib = "0.2.8"
elementtree = "0"